package at.dasher.android

import android.content.Context
import org.json.JSONObject
import java.io.File

/** Shared prefs keys for locale-follow (used by MainActivity + SettingsScreen). */
object AlphabetPrefs {
    const val PREFS = "dasher_input"
    const val KEY_FOLLOWS_LOCALE = "alphabet_follows_locale"
}

/**
 * Alphabet metadata index (DasherCore `Data/alphabets/alphabet_index.json`,
 * generated by `Scripts/generate-alphabet-index.py`). One entry per unique
 * alphabet: lang code, ISO-15924 script, direction, corpus tier, symbol count.
 *
 * Uses:
 *  - Locale-follow: pick a sensible default alphabet for the device locale
 *    (only while the user hasn't explicitly chosen one).
 *  - Picker badges: script / direction / lang next to each alphabet name.
 *
 * Falls back to an empty index when the file is missing or unreadable — the
 * engine's own name scan (CAlphIO::ScanNameIndex) is independent, so the
 * app keeps working; only the metadata niceties degrade.
 */
data class AlphabetInfo(
    val id: String,
    val orientation: String,
    val lang: String?,
    val script: String?,
    val scriptName: String?,
    val chars: Int,
    val source: String,
) {
    val rtl: Boolean get() = orientation == "rtl"
}

object AlphabetIndex {

    /** The engine's historical default — preferred within its tier for locale-follow. */
    const val ENGINE_DEFAULT_ALPHABET = "English with limited punctuation"

    @Volatile
    private var cached: List<AlphabetInfo>? = null

    fun get(context: Context): List<AlphabetInfo> {
        cached?.let { return it }
        val loaded = load(context)
        cached = loaded
        return loaded
    }

    private fun load(context: Context): List<AlphabetInfo> {
        // Extracted copy first (DataInstaller always runs before the engine
        // starts); the APK asset is the pre-extraction fallback.
        val extracted = File(context.filesDir, "dasher_data/alphabets/alphabet_index.json")
        val text = try {
            if (extracted.exists()) extracted.readText()
            else context.assets.open("alphabets/alphabet_index.json").bufferedReader().use { it.readText() }
        } catch (_: Exception) {
            return emptyList()
        }
        return try {
            val arr = JSONObject(text).getJSONArray("alphabets")
            (0 until arr.length()).mapNotNull { i ->
                val o = arr.getJSONObject(i)
                AlphabetInfo(
                    id = o.getString("id"),
                    orientation = o.optString("orientation", "ltr"),
                    lang = o.optString("lang").ifEmpty { null },
                    script = o.optString("script").ifEmpty { null },
                    scriptName = o.optString("script_name").ifEmpty { null },
                    chars = o.optInt("chars", 0),
                    source = o.optString("source", "legacy"),
                )
            }
        } catch (_: Exception) {
            emptyList()
        }
    }

    /**
     * Best alphabet for a BCP-47 locale tag ("ar", "pt-BR", "zh-Hans-CN").
     * Match order: exact lang code, then language+script ("zh-Hans" → an
     * alphabet with lang zh-Hans), then language prefix. Ranking within the
     * matched set: maintained > worldalphabets > legacy, the engine's
     * historical default alphabet ("English with limited punctuation")
     * first within its tier, then fuller alphabets.
     *
     * The tier order matters more than it looks: the autoconverted
     * WorldAlphabets files have a pre-existing engine bug where their trees
     * barely expand (DasherCore issue TBD) — defaulting onto one renders a
     * flat, unweighted-looking canvas. Defaults must land on maintained
     * alphabets; WA stays a deliberate choice.
     */
    fun suggestForLocale(context: Context, localeTag: String): AlphabetInfo? =
        suggestFrom(get(context), localeTag)

    /** Pure form of [suggestForLocale] (unit-testable, no Context). */
    fun suggestFrom(list: List<AlphabetInfo>, localeTag: String): AlphabetInfo? {
        if (list.isEmpty()) return null

        val tag = localeTag.replace('_', '-')
        val language = tag.substringBefore('-').lowercase()
        if (language.isEmpty()) return null
        val script = tag.split('-').getOrNull(1)?.takeIf { it.length == 4 }?.replaceFirstChar { it.uppercase() }

        fun tier(a: AlphabetInfo) = when (a.source) {
            "maintained" -> 0
            "worldalphabets" -> 1
            else -> 2
        }

        // Score: better (lower) tier dominates; within a tier the engine
        // default wins, then the fuller alphabet. The previous version
        // multiplied the tier INTO the score (tier 1 beat tier 0) — every
        // locale followed onto a WorldAlphabets variant.
        fun score(a: AlphabetInfo): Long {
            val tierRank = 2L - tier(a) // maintained (tier 0) → highest rank
            val defaultBonus = if (a.id == ENGINE_DEFAULT_ALPHABET) 1L else 0L
            return tierRank * 1_000_000L + defaultBonus * 500_000L + a.chars.coerceAtMost(499_999)
        }

        val candidates = list.filter { !it.lang.isNullOrEmpty() }
        // 1. exact lang code (covers "zh-Hans" style entries directly)
        candidates.filter { it.lang!!.equals(tag, ignoreCase = true) }
            .maxByOrNull { score(it) }
            ?.let { return it }
        // 2. language + script ("zh-Hans-CN" → lang "zh-Hans")
        if (script != null) {
            candidates.filter { it.lang == "$language-$script" }
                .maxByOrNull { score(it) }
                ?.let { return it }
        }
        // 3. language prefix
        return candidates.filter { it.lang!!.startsWith(language) }
            .maxByOrNull { score(it) }
    }
}
